version: "3.4"
services:
  db:
    image: postgres:13
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
